export const queueData = [
  {
    avatar: "https://picsum.photos/200",
    name: "Atta Junior",
    date: "Today",
    time: "5:00",
    waitTime: 10,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/201",
    name: "Emma Thompson",
    date: "Today",
    time: "5:15",
    waitTime: 15,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/202",
    name: "Liam Neeson",
    date: "Today",
    time: "5:30",
    waitTime: 20,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/203",
    name: "Sophia Chen",
    date: "Today",
    time: "5:45",
    waitTime: 25,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/204",
    name: "Mohammed Al-Fayed",
    date: "Today",
    time: "6:00",
    waitTime: 30,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/205",
    name: "Isabella Rossi",
    date: "Today",
    time: "6:15",
    waitTime: 35,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/206",
    name: "Jamal Wilson",
    date: "Today",
    time: "6:30",
    waitTime: 40,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/207",
    name: "Olivia Parker",
    date: "Today",
    time: "6:45",
    waitTime: 45,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/208",
    name: "Ethan Hunt",
    date: "Today",
    time: "7:00",
    waitTime: 50,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/209",
    name: "Zoe Rodriguez",
    date: "Today",
    time: "7:15",
    waitTime: 55,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/210",
    name: "Aiden O'Brien",
    date: "Today",
    time: "7:30",
    waitTime: 60,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/211",
    name: "Mia Tanaka",
    date: "Today",
    time: "7:45",
    waitTime: 65,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/212",
    name: "Lucas Müller",
    date: "Today",
    time: "8:00",
    waitTime: 70,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/213",
    name: "Chloe Dubois",
    date: "Today",
    time: "8:15",
    waitTime: 75,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/214",
    name: "Hassan Ahmed",
    date: "Today",
    time: "8:30",
    waitTime: 80,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/215",
    name: "Freya Larsson",
    date: "Today",
    time: "8:45",
    waitTime: 85,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/216",
    name: "Diego Hernandez",
    date: "Today",
    time: "9:00",
    waitTime: 90,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/217",
    name: "Yuki Sato",
    date: "Today",
    time: "9:15",
    waitTime: 95,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/218",
    name: "Ava Patel",
    date: "Today",
    time: "9:30",
    waitTime: 100,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/219",
    name: "Leo Kowalski",
    date: "Today",
    time: "9:45",
    waitTime: 105,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/220",
    name: "Zara Al-Mansour",
    date: "Today",
    time: "10:00",
    waitTime: 110,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/221",
    name: "Oscar Andersson",
    date: "Today",
    time: "10:15",
    waitTime: 115,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/222",
    name: "Amelia Cheng",
    date: "Today",
    time: "10:30",
    waitTime: 120,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/223",
    name: "Noah van der Berg",
    date: "Today",
    time: "10:45",
    waitTime: 125,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/224",
    name: "Lila Nkosi",
    date: "Today",
    time: "11:00",
    waitTime: 130,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/25",
    name: "Atta Junior",
    date: "Today",
    time: "5:00",
    waitTime: 10,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/24",
    name: "Emma Thompson",
    date: "Today",
    time: "5:15",
    waitTime: 15,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/23",
    name: "Liam Neeson",
    date: "Today",
    time: "5:30",
    waitTime: 20,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/22",
    name: "Sophia Chen",
    date: "Today",
    time: "5:45",
    waitTime: 25,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/21",
    name: "Mohammed Al-Fayed",
    date: "Today",
    time: "6:00",
    waitTime: 30,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/20",
    name: "Isabella Rossi",
    date: "Today",
    time: "6:15",
    waitTime: 35,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/19",
    name: "Jamal Wilson",
    date: "Today",
    time: "6:30",
    waitTime: 40,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/18",
    name: "Olivia Parker",
    date: "Today",
    time: "6:45",
    waitTime: 45,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/17",
    name: "Ethan Hunt",
    date: "Today",
    time: "7:00",
    waitTime: 50,
    type: "withdraw",
  },
  {
    avatar: "https://picsum.photos/16",
    name: "Zoe Rodriguez",
    date: "Today",
    time: "7:15",
    waitTime: 55,
    type: "special",
  },
  {
    avatar: "https://picsum.photos/15",
    name: "Aiden O'Brien",
    date: "Today",
    time: "7:30",
    waitTime: 60,
    type: "special",
  },
  {
    avatar: "https://picsum.photos/14",
    name: "Mia Tanaka",
    date: "Today",
    time: "7:45",
    waitTime: 65,
    type: "special",
  },
  {
    avatar: "https://picsum.photos/13",
    name: "Lucas Müller",
    date: "Today",
    time: "8:00",
    waitTime: 70,
    type: "special",
  },
  {
    avatar: "https://picsum.photos/12",
    name: "Chloe Dubois",
    date: "Today",
    time: "8:15",
    waitTime: 75,
    type: "special",
  },
  {
    avatar: "https://picsum.photos/11",
    name: "Hassan Ahmed",
    date: "Today",
    time: "8:30",
    waitTime: 80,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/10",
    name: "Freya Larsson",
    date: "Today",
    time: "8:45",
    waitTime: 85,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/9",
    name: "Diego Hernandez",
    date: "Today",
    time: "9:00",
    waitTime: 90,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/8",
    name: "Yuki Sato",
    date: "Today",
    time: "9:15",
    waitTime: 95,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/7",
    name: "Ava Patel",
    date: "Today",
    time: "9:30",
    waitTime: 100,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/6",
    name: "Leo Kowalski",
    date: "Today",
    time: "9:45",
    waitTime: 105,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/5",
    name: "Zara Al-Mansour",
    date: "Today",
    time: "10:00",
    waitTime: 110,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/4",
    name: "Oscar Andersson",
    date: "Today",
    time: "10:15",
    waitTime: 115,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/3",
    name: "Amelia Cheng",
    date: "Today",
    time: "10:30",
    waitTime: 120,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/2",
    name: "Noah van der Berg",
    date: "Today",
    time: "10:45",
    waitTime: 125,
    type: "deposit",
  },
  {
    avatar: "https://picsum.photos/1",
    name: "Lila Nkosi",
    date: "Today",
    time: "11:00",
    waitTime: 130,
    type: "deposit",
  },
];
